language: node_js
node_js:
  - "0.10"
  - "0.8"
before_install:
  - wget http://phantomjs.googlecode.com/files/phantomjs-1.9.0-linux-i686.tar.bz2
  - tar -xvf phantomjs-1.9.0-linux-i686.tar.bz2
  - sudo mv phantomjs-1.9.0-linux-i686/bin/phantomjs `which phantomjs`
  - wget https://github.com/n1k0/casperjs/archive/1.0.2.tar.gz -nv -O - | tar zx
  - sudo ln -s `pwd`/casperjs-1.0.2/bin/casperjs /usr/local/bin/casperjs
  - npm install grunt-cli
  - phantomjs --version
  - casperjs --version
script: grunt test_travis
