language: node_js
node_js:
  - "0.10"
  - "0.8"
before_install:
  - mkdir ~/bin
  - export PATH=$PATH:~/bin
  - git clone git://github.com/n1k0/casperjs.git
  - cd casperjs
  - git checkout tags/1.0.2
  - ln -sf `pwd`/bin/casperjs ~/bin/casperjs
  - cd ../
  - npm install grunt-cli
before_script:
  - phantomjs --version
  - casperjs --version
