language: node_js
node_js:
  - "0.10"
  - "0.8"
before_install:
  - export PATH=$PATH:~/bin
  - echo "PATH: $PATH"
  - phantomjs --version
  - echo "installing CasperJS 1.0.2"
  - git clone git://github.com/n1k0/casperjs.git
  - cd casperjs
  - git checkout tags/1.0.2
  - ln -sf `pwd`/bin/casperjs ~/bin/casperjs
  - echo "installing grunt-cli"
  - cd ../
  - npm install grunt-cli
