language: node_js
node_js:
  - "0.10"
before_script:
  - wget https://github.com/n1k0/casperjs/archive/1.0.2.tar.gz -nv -O - | tar zx
  - sudo ln -s `pwd`/casperjs-1.0.2/bin/casperjs /usr/local/bin/casperjs
  - npm install grunt-cli
  - phantomjs --version
  - casperjs --version
script: grunt test_travis
